### PR TITLE
fix zts build in PHP7

### PR DESCRIPTION
**Pull request by krakjoe**
We fixed this yesterday already, but it seems to have come back ;)

### CODE REVIEW

**Comment by krakjoe** [comment]
I

**Comment by RyanNerd** [comment]
I recompiled xdebug with the patch and I'm still getting the Process finished with exit code 139. 
I double checked that the changes to xdebug_var.c were there.
I also did a 'make clean' command.

PHPStorm flashes as if it is about to let me step into the code, but then dies.

**Comment by derickr** [comment]
PHP 7 support is nowhere near ready @RyanNerd

**Comment by RyanNerd** [comment]
Is there an ETA for an alpha release of PHP 7 support? In other words I'd
like to help with the alpha testing phase of xdebug.
I'd offer to help with the C coding, but it has been 15 years since I coded
in C, and this Zend library/API confuses the heck out of me.

**Pull request closed without merging**
